apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::805392809179:role/eksNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::805392809179:role/codebuild-eks
      username: codebuild-eks
      groups:
        - system:masters        
  mapUsers: |
    - userarn: arn:aws:iam::805392809179:user/harshad.n@minfytech.com
      username: harshad.n@minfytech.com
      groups:
        - system:masters
