apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production-db
  template:
    metadata:
      name: mydb-pod
      labels:
        env: production-db
    spec:
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: database
        image: mysql:5.7
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: redhat
         - name: MYSQL_ROOT_PASSWORD
           value: dummypassword
         - name: MYSQL_USER
           value: raghav
         - name: MYSQL_PASSWORD
           value: redhat
         - name: MYSQL_DATABASE
           value: mydbldb
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-vol


      
