apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjava-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production-frontend
  template:
    metadata:
      name: myfrontend-pod
      labels:
        env: production-frontend
    spec:
      containers:
      - name: frontend
        image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: RDS_HOSTNAME
          value: "app-mysql"
        - name: RDS_PORT
          value: "3306"
        - name: RDS_DB_NAME
          value: "mydbldb"
        - name: RDS_USERNAME
          value: "raghav"
        - name: RDS_PASSWORD
          value: "redhat"

